### PR TITLE
Adding documentation on how to install CLI dependencies to run the Unit Tests

### PR DESCRIPTION
**Pull request by rodolfomp123**
This PR adds documentation to the `running_unit_tests.md` file to describe how to install the CLI dependencies required for running the unit tests.
The documentation includes the necessary steps and commands to install the dependencies.

### CODE REVIEW

**Comment by darjeeling** [comment]
I think this change based on specific platform. I think we need to address that.

**Comment by rodolfomp123** [comment]
Hey @darjeeling ! Thanks for pointing that out! I just fixed it considering all platforms.

**Comment by ehmatthes** [comment]
Thank you for this! I have not had a chance to pull these larger PRs and look at them locally yet, but I should be able to do that tonight or tomorrow morning.

**Comment by ehmatthes** [comment]
Okay, I've just had a chance to take a good look at this. First of all, thank you for writing this up. I think this relates to #223 and #230 as well.

I think we are going to use what you wrote up here, but not in the unit test documentation. I'm not sure how much people have dug into the codebase, but briefly here's what happens:

- In [simple_deploy.py](https://github.com/ehmatthes/django-simple-deploy/blob/main/simple_deploy/management/commands/simple_deploy.py), we do all platform-agnostic work, mostly focusing on inspecting the local project. Note there are also some platform-agnostic utility methods in here that the platform-specific files use.
- In simple_deploy.py, `handle()` [coordinates](https://github.com/ehmatthes/django-simple-deploy/blob/main/simple_deploy/management/commands/simple_deploy.py#L58) most of the configuration work.
-  At some point in simple_deploy.py, it [calls out](https://github.com/ehmatthes/django-simple-deploy/blob/main/simple_deploy/management/commands/simple_deploy.py#L80) to `platform_deployer.validate_platform()`.  This is a chance for the platform-specific object to do some inspection as well, before making any changes to the user's project.
- Using Fly.io as an example, the platform-specific configuration happens in [deploy.py](https://github.com/ehmatthes/django-simple-deploy/blob/main/simple_deploy/management/commands/fly_io/deploy.py).
- In deploy.py, in [validate_platform()](https://github.com/ehmatthes/django-simple-deploy/blob/main/simple_deploy/management/commands/fly_io/deploy.py#L335), we call `_validate_cli()`.

**I think we want to skip that call to `_validate_cli()` when running unit tests.** One major goal of unit testing is to not make any network calls. I don't believe we're using the CLI at all during unit tests. My guess is a quick disabling of this will not affect unit tests; I haven't tried this. There are a number of other actions that are disabled during unit testing, such as [setting secrets](https://github.com/ehmatthes/django-simple-deploy/blob/main/simple_deploy/management/commands/fly_io/deploy.py#L58) on the target platform.

I think the place for this information is in the documentation for the integration tests. I think this is very useful information for contributors; it saves you from having to look up the installation instructions for your target platform. I'm not even sure about that though; integration tests are not meant to be run as a comprehensive test suite; it just takes too long, and is too resource intensive. Also, imagine this project when it supports ten platforms. No one should have to have ten platform CLIs installed, especially when you have to have a CC registered to make an account on all these platforms.

What do you think?

**Comment by ehmatthes** [comment]
I'm going to close this, because the requirement for CLIs to be installed for unit test runs was removed in #236. But I have added this to #195, where we will use this documentation. Thank you!

**Pull request closed without merging**
